Mooc/Mooc/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^w96284aj4dk4/', include(admin.site.urls)),
    url(r'^', include('courses.urls', namespace='courses',app_name='courses')),
    url(r'^accounts/', include('users.urls', namespace='users', app_name='users')),
    ]

Mooc/courses/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib.auth.views import password_change_done
from django.contrib import admin
from .views import *


urlpatterns = [
    url(r'^$', home, name='home', ),
    url(r'^addcourses/$', addcourses, name='addcourses', ),
    url(r'^admin/$', include(admin.site.urls)),
    url(r'^deleteCourses/(?P<pk>\d+)/$', deleteCourses, name='deleteCourses', ),
    url(r'^keywords/(?P<pk>\d+)/$',keywords, name='keywords',),
    url(r'^deletekeywords/(?P<pk>\d+)/$',deletekeywords, name='deletekeywords', ),
    url(r'^addkeywords/(?P<pk>\d+)$',addkeywords, name='addkeywords', )
]

Mooc/users/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.auth.views import password_change_done
from .views import *


urlpatterns = [
    url(r'^signup/', signup_view, name='signup', ),
    url(r'^valid/', valid_view, name='valid', ),
    url(r'^login/', login_view, name='login', ),
    url(r'^logout/', logout_view, name='logout', ),
    # url(r'^password-change/$', password_change_view, name='password_change'),
    # url(r'^password-change/done/$',
    #     password_change_done, name='password_change_done'),
]

Mooc/templates/component/login_alert_modal.html
{% load i18n %}

<div class="modal fade" id="LoginAlertModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">{% trans 'Oops!' %}</h4>
      </div>
      <div class="modal-body">
        <p>{% trans 'Please Login first.' %}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Cancel' %}</button>
        <a type="button" class="btn btn-primary" href="{% url 'users:login' %}">{% trans 'Login' %}</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

Mooc/templates/component/navbar.html
{% load i18n %}

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'courses:home'%}">NTU MOOCs Analysis Platform</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">



      <ul class="nav navbar-nav navbar-right">
        
        {% if request.session.User  %}
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.session.User }}<span class="caret"></span></a>
          </li>
          <li><a href="{% url 'users:logout' %}">{% trans 'Logout' %}</a></li>
        {% else %}
          <li>
            <a href="{% url 'users:login' %}">{% trans 'Log In' %}</a>
          </li>
           <li>
            <a href="{% url 'users:signup' %}">{% trans 'Sign Up' %}</a>
          </li>
        {% endif %}

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

Mooc/templates/component/news_comment.html
{% extends 'base.html' %}

{% load i18n %}

{% load crispy_forms_tags %}

{% block body %}
<form method="POST" action="." >
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" name="submit" class="btn btn-primary text-center">{% trans 'comment' %}</button>     
</form>
{% endblock %}

Mooc/templates/component/ticket_confirm_modal.html
{% load i18n %}

{% if panel == 'giveout' %}
<div class="modal fade" id="GiveoutTicketConfirmModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">{% trans 'Ticket Confirmation' %}</h4>
      </div>
      <div class="modal-body">
        <p>{% trans 'Are you sure you want to release this giveout ticket ?' %}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Cancel' %}</button>
        <button type="submit" name="giveout-ticket-submit" class="btn btn-primary">{% trans 'Confirm' %}</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% elif panel == 'exchange' %}
<div class="modal fade" id="ExchangeTicketConfirmModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">{% trans 'Ticket Confirmation' %}</h4>
      </div>
      <div class="modal-body">
        <p>{% trans 'Are you sure you want to release this exchange ticket ?' %}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Cancel' %}</button>
        <button type="submit" name="exchange-ticket-submit" class="btn btn-primary">{% trans 'Confirm' %}</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endif %}