Mooc/Mooc/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^w96284aj4dk4/', include(admin.site.urls)),
    url(r'^', include('courses.urls', namespace='courses',app_name='courses')),
    url(r'^accounts/', include('users.urls', namespace='users', app_name='users')),
    ]

Mooc/courses/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib.auth.views import password_change_done
from django.contrib import admin
from .views import *


urlpatterns = [
    url(r'^$', home, name='home', ),
    url(r'^addcourses/$', addcourses, name='addcourses', ),
    url(r'^admin/$', include(admin.site.urls)),
    url(r'^deleteCourses/(?P<pk>\d+)/$', deleteCourses, name='deleteCourses', ),
    url(r'^keywords/(?P<pk>\d+)/$',keywords, name='keywords',),
    url(r'^deletekeywords/(?P<pk>\d+)/$',deletekeywords, name='deletekeywords', ),
    url(r'^addkeywords/(?P<pk>\d+)$',addkeywords, name='addkeywords', )
]

Mooc/templates/addcourses.html
{% extends 'base.html' %}

{% load i18n %}

{% load crispy_forms_tags %}

{% block body-class %}user{% endblock %}

{% block body %}
<div class="container">
	<div class="field-box col-sm-6 col-sm-offset-3">
		<div class="row">	
			<h2 class="text-center">{% trans '開設課程 !' %}</h2>
		</div>
		<div class="row">
			<div class="col-sm-offset-1 col-sm-10">
				<form method="post">
				    {% csrf_token %}
				    {{ form|crispy }}
				    <button type="submit" name="submit" value="Sign Up" id="submit" class="btn btn-primary text-center col-sm-12 User-btn">{% trans '開設' %}</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

Mooc/templates/addkeywords.html
{% extends 'base.html' %}

{% load i18n %}

{% load crispy_forms_tags %}

{% block body-class %}user{% endblock %}

{% block body %}
<div class="container">
	<div class="field-box col-sm-6 col-sm-offset-3">
		<div class="row">	
			<h2 class="text-center">{% trans '加入關鍵字 !' %}</h2>
		</div>
		<div class="row">
			<div class="col-sm-offset-1 col-sm-10">
				<form method="post">
				    {% csrf_token %}
				    {{ form|crispy }}
				    <button type="submit" name="submit" value="Sign Up" id="submit" class="btn btn-primary text-center col-sm-12 User-btn">{% trans '加入' %}</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

Mooc/templates/base.html
<!DOCTYPE html>
{% load static %}

{% load i18n %}
{% load compress static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="description" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  {% block head_tags %}
  {% endblock %}
  <link rel="icon" type="image/x-icon" href="{% static 'image/fox.ico' %}"  sizes="32x32"/>

  <link href='https://fonts.googleapis.com/earlyaccess/cwtexkai.css' rel='stylesheet' type='text/css'>

  <link href='//fonts.googleapis.com/css?family=Varela+Round:300,400,500,700' rel='stylesheet' type='text/css'>


  {% compress css %}
      <link rel="stylesheet" type="text/x-scss" href="{% static 'css/main.scss' %}">
  {% endcompress %}


  {% block extra_css %}
  {% endblock %}

  <title>{% block title %}NTU MOOC Management Platform{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.structure.min.css">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.theme.min.css">

        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.1/jquery.validate.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.1.1/masonry.pkgd.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.1/imagesloaded.pkgd.min.js"></script>
</head>


<body class="{% block body-class %}{% endblock %}">

    {% include "component/navbar.html" %}

    {% block body %}
    {% endblock %}

    {% compress js %}
        <script type="text/javascript" src="{% static 'js/csrf_token.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/datepicker-zh-TW.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
        {% block scripts %}{% endblock %}
    {% endcompress %}

    {% block extra_js %}

    {% endblock %}
<script>
  {% get_current_language as LANGUAGE_CODE %}
  {% if LANGUAGE_CODE == 'zh-hant' %}
    $('.dateinput').datepicker($.datepicker.regional["zh-TW"]);
  {% else %}
    $('.dateinput').datepicker($.datepicker.regional[""]);
  {% endif %}
</script>

</body>
</html>

Mooc/templates/home.html
{% extends 'base.html' %}

{% load i18n %}

{% block body-class %}home{% endblock %}

{% block body %}

  


<!-- Tab panes -->



{% if request.session.User %} 
<div class="EventBlock" style="margin-left: 7.5%; margin-right: 7.5%" > 
 <div class="tab-content container">
 <h3>開設課程清單:</h3> 
      <a class="btn" style="background-color:#FFFFFF" href="{% url 'courses:addcourses' %}">{% trans '開設課程' %}</a>
    <br>
    <br>
    <div role="tabpanel" class="tab-pane active" id="popular">
      <div class="row masonry-container">
        {% for course in own_list %}
        <div class="col-sm-4 EventBlock-event">
          <div class="EventBlock-event-box">
              <div class="EventBlock-event-img">      
              </div>
              <h4>{{ course.coursename }}</h4>
            </a>
          </div>
          <br>  
          <a class="btn" style="background-color:#FFFFFF" href="{% url 'courses:keywords' pk=course.relationid %} ">{% trans '編輯關鍵字' %}</a>
        </div>
        {% endfor %}
      </div><!--End masonry-container  -->
    </div>
 </div>
 </div>

{% else %}
<img class="img-responsive" src="/static/image/mooc.png" alt="">
      
{% endif %}



    <!-- Recent tabpanel -->
    
{% endblock%}

Mooc/templates/keyword.html
{% extends 'base.html' %}

{% load i18n %}

{% block body-class %}home{% endblock %}

{% block body %}

  


<!-- Tab panes -->


<div class="EventBlock" style="margin-left: 7.5%; margin-right: 7.5%" >
  <!-- Popular tabpanel -->
  <div class="tab-content container  ">
  <h3 >StopWord清單:</h3>
  <a class="btn" style="background-color:#FFFFFF" href="{% url 'courses:addkeywords' pk=db_number %}">{% trans '加入關鍵字' %}</a>
    <div role="tabpanel" class="tab-pane active" id="popular">
      <div class="row masonry-container">
        {% for keyword in word_list %}
        <div class="col-sm-4 EventBlock-event">
          <div class="EventBlock-event-box">
              <h4>{{ keyword.stopword }}</h4>
              <a class="btn" style="background-color:#FFFFFF" href="{% url 'courses:deletekeywords' pk=keyword.id %} ">{% trans '刪除關鍵字' %}</a>
            </a>
          </div>
        </div>
        {% endfor %}
      </div><!--End masonry-container  -->
    </div>
  </div>
</div>




    <!-- Recent tabpanel -->
    
{% endblock%}